### ISSUE TITLE
Constant Time

### ISSUE THREAD

**Issue by azet** [ricmoo/aes-js#1]
Hi,

The README file does not mention if the implementation is in constant-time, can you maybe shed some light on that matter?

Thanks

**Comment by ricmoo** [comment]
Ahoy hoy,

I'm assuming you are referring to the time-complexity? The AES block cipher is constant time, O(1). And each of the modes of operations run the AES block cipher O(n) times (where n is the length of data being encrypted/decrypted [in blocks]). So, the overall time complexity to encrypt or decrypt n bytes is O(n).

However, when speaking of cryptography, it is important to understand that constant-time is not protection against side-channel attacks. Specifically, since this implementation is written in JavaScript, it is important to understand [timing attack](https://en.wikipedia.org/wiki/Timing_attack). Due to garbage collection, caching, branch predicates and many other interesting optimizations, you may leak information inadvertently without careful use.

Does that make sense?

**Comment by azet** [comment]
Hi @ricmoo 

Yes it does, thanks for taking the time. 'Constant-time' was a bad description, I was thinking about side-channel attacks, yes. Thanks for the explanation.

**Comment by ricmoo** [comment]
No problem. :)
