### ISSUE TITLE
convertBytesToString/convertStringToBytes question

### ISSUE THREAD

**Issue by fresheneesz** [ricmoo/aes-js#11]
Either `convertBytesToString` or `convertStringToBytes` is bugging out in this case:

```
var bytes = [182,42,190,168]
var text2 = aes.util.convertBytesToString(bytes)
var bytes2 = aes.util.convertStringToBytes(text2)

console.log(bytes)
console.log(text2)
console.log(bytes2)
```

This is causing decryption (or possibly encryption) to fail for me.

**Comment by fresheneesz** [comment]
Instead of using these methods to serialize, I'm using `buffer.toString('base64')` and `new Buffer(base64Text,'base64)`

**Comment by ricmoo** [comment]
Hey @fresheneesz,

Where did you get that series of bytes from? It doesn't seem to be a valid UTF-8 string. Not every series of bytes is a valid UTF-8 string. That function is meant to convert a valid UTF-8 string to bytes and vice versa.

There is certainly some more investigation I need to do, because this also fails to match those results:

```javascript
> new Buffer((new Buffer([182,42,190,168])).toString(), 'utf8')
<Buffer ef bf bd 2a ef bf bd ef bf bd>
```

Are you passing this in as the key? You should also look at using a key-derivation function (such as crypt, crypt, scrypt, et cetera). Also, check out this section on normalizing the encoding: https://github.com/ricmoo/scrypt-js#encoding-notes

You should be able to just pass a buffer directly into `aes` as well...

**Comment by fresheneesz** [comment]
I got this error while encrypting data that contained RSA keys in standard format. After encrypting, I stored the result of convertBytesToString in localStorage, but when getting back from storage and using convertStringToBytes, it was mangled. I took just a little bit of the bytes array to make this minimal repro. It seems a bit problematic that a function like this would only work for data in a certain format - isn't this data supposed to be pretty arbitrary? In any case, I'm using them before encryption and after decryption without issue - it just seems a bit broken when used after encryption or before decryption.

**Comment by ricmoo** [comment]
Oh, that will definitely fail then. :)

So, a `String` is a piece of data representing text in a specific encoding, in the case of `encoding` not being specified, it defaults to UTF-8 which has very specific rules. So, arbitrary binary data will quite often not follow these rules. See [invalid sequences](https://en.wikipedia.org/wiki/UTF-8#Invalid_byte_sequences).

Also, UTF-8 encoding and decoding is not necessarily symmetric, `decode(encode(data)) != data` is not always true. The above notes on UTF normalization can give you some examples.

When encrypting and decrypting data, binary output is produced, which is why it is incompatible with UTF-8.

For your purposes, you may wish to store the string encoded as a hex string, by using:

```javascript
var hexString = aes.util.convertBytesToString(bytes, "hex");
var original = aes.util.convertStringToBytes(hexString, "hex")
```

But base64 is fine too (I don't provide a base64 encoder/decoder in *aes-js* though), the important thing is these encodings (hex, base64, uuencode, et cetera) is that they are specifically designed to represent binary data using only printable ASCII bytes, while UTF-8 is not.

Here is more information on binary-to-text encodings: https://en.wikipedia.org/wiki/Binary-to-text_encoding

Hope that helps.

**Comment by fresheneesz** [comment]
Gotcha. Might be a good idea to rename these to something like `convertUTFBytesToString`, cause the name makes me think its more general.

**Comment by ricmoo** [comment]
Yeah, or maybe enforcing an encoding is passed in and not just defaulting to 'utf8'...

Thanks for feedback. :)

**Comment by RicardoArauj0** [comment]
Hi how are you?
I'm trying to use aes-js on node:

var key = [ '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'r', 'i', 'u', 'k', 'a', 'v']
var aesCtr = new aesjs.ModeOfOperation.ctr(key, new aesjs.Counter(5));

On the line 2 I receive the error: "Array contains invalid value 0,".
Do you know whats this could be?

I appreciate your help in advance.

**Comment by RicardoArauj0** [comment]
I just did it. I used the Buffer key instead of the intArray one.
