### ISSUE TITLE
The length of plaintext in CBC

### ISSUE THREAD

**Issue by captainbupt** [ricmoo/aes-js#16]
Based on my understanding, the CBC mode works for any plaintext which length is multiple of segment size. If there is automatically padding mechanism, the length of plaintext can be any. 
But in your implementation, this length of plaintext is required to be 16 bytes, which is hard to use in real cases. Hope that you would take it into consideration : )

**Comment by ricmoo** [comment]
You are absolutely correct, I keep saying I will get around to this. It should apply to any mode as long as the length requirements are valid. I will aim to add it (and relevant test cases) this weekend.

CBC and ECB should both accept any input so long as its length is congruent to 0 mod 16.

**Comment by ricmoo** [comment]
I've added this functionality to the repository and updated the test cases and test vectors, but have not published it on npm (nor set a version tag for bower) yet... I want to test it a bit more before pushing it out where it will automatically get picked up. If you have a moment, can you give it a try?

I will get a peer code review tomorrow, and welcome any code review from you and anyone else. :)

Thanks!

**Comment by tryadelion** [comment]
any way to bypass this problem?

**Comment by ricmoo** [comment]
The master code works, not the latest npm package though. Do you need the npm package? I can publish it tonight, I was just hoping to get a few ACKs that it worked for people. :)

**Comment by tryadelion** [comment]
i'm using the html include, it's an ionic project.

**Comment by tryadelion** [comment]
so far i haven't been able to decrypt the results in any online decryptor or on my own php server to test it.

**Comment by swansontec** [comment]
Hah! I just finished writing a loop to feed data through the CBC mode one block at a time, but now I see you've already got code like this cooking upstream. Let me try this when I get back to work tomorrow.

**Comment by ricmoo** [comment]
@tryadelion Are you using mCrypt? I have another conversation over e-mail with someone who is using the PHP library, and it seems that they call the OFB mode of operation, NOFB.

If you want to avoid padding (PKCS#7 or otherwise), I would recommend using the CTR (counter) mode of operation. OFB works fine too, for non-block-sized (16 bytes) input data.

**Comment by tryadelion** [comment]
will try that! i'm actually trying to find any compatible php library, so, if you know of a working setup, i'm glad to hear about it.

**Comment by swansontec** [comment]
@ricmoo I've adapted my project to the latest (unreleased) version of aes-js, and can verify that your AES-CBC code looks good. All my unit tests are passing, and a quick code-review of your changes seems solid.

**Comment by ricmoo** [comment]
@swansontec Awesome, thanks!

I've published it to NPM as version 2.1.0 as well as added the tag for bower.

This issue has become about 2 issues. I'm going to close this as the issue relating to CBC/ECB length and open a new issue regarding updating the documentation for the PHP/mCrypt issues.

**Comment by edele** [comment]
BTW it still says CBC payload must be 16 bytes in docs https://github.com/ricmoo/aes-js#cbc---cipher-block-chaining-recommended

I'm just trying that out and it would be handy to know whether padding is automatically applied and what type of padding it is.

**Comment by ricmoo** [comment]
Thanks! I forgot to update the docs.

I will update it tomorrow to reflect the fact that the input must be a multiple of 16 bytes (not exactly 16 bytes).

Padding is never automatically added, since there are common reasons to not pad (PKCS#7 padding will always increase its length, and for example a secret storage key is always 32 bytes which can use aes-cbc to store as 32 bytes, but automatically padding would make it 48 bytes) and padding cannot automatically be trimmed, since if t wasn't padded, you are corrupting the data.

Padding is part of a higher level decision of a protocol than the block cipher can decide.

Does that make sense? Let me know if I should add more clarification. I should probably add a section describing how and when padding should/could be used and why it is necessary for the protocol to define what padding should be used.

**Comment by edele** [comment]
Thanks!

I padded it myself using https://www.npmjs.com/package/pkcs7

```
var aesCbc = new aesjs.ModeOfOperation.cbc(key, iv);
var encryptedBytes = aesCbc.encrypt(pkcs7.pad(textBytes));
```

**Comment by ricmoo** [comment]
Oh, PKCS#7 is available in the library, just not done automatically.

```javascript
var aesCbc = new aesjs.ModeOfOperation.cbc(key, iv);
var encryptedBytes = aesCbc.encrypt(aesjs.padding.pkcs7.pad(textBytes));
```

I see now that I also missed documenting that in the README... I'll add that shortly too.

Thanks for pointing that out.

**Comment by ricmoo** [comment]
Yeah, I think it’s documentation only exists in a probably closed issue. I need to refactor the AES library along with the scrypt library in general.

It’s on my backlog. Let me put it on my calendar for this weekend. *crosses fingers*
