### ISSUE TITLE
bytesToString / stringToBytes seems destructive

### ISSUE THREAD

**Issue by wvervuurt** [ricmoo/aes-js#17]
Thanks for your fantastic code, really helpful!

I have this issue: stringToBytes(bytesToString(input)) != input

When I run this CTR example, everything works nicely:
```
var key = aesjs.util.convertStringToBytes("Example128BitKey");

// Convert text to bytes
var text = 'Text may be any length you wish, no padding is required.';
var textBytes = aesjs.util.convertStringToBytes(text);

// The counter is optional, and if omitted will begin at 0
var aesCtr = new aesjs.ModeOfOperation.ctr(key, new aesjs.Counter(5));
var encryptedBytes = aesCtr.encrypt(textBytes);

// The counter mode of operation maintains internal state, so to
// decrypt a new instance must be instantiated.
var aesCtr = new aesjs.ModeOfOperation.ctr(key, new aesjs.Counter(5));
var dec:ryptedBytes = aesCtr.decrypt(encryptedBytes);

// Convert our bytes back into text
var decryptedText = aesjs.util.convertBytesToString(decryptedBytes);
console.log(decryptedText);
// "Text may be any length you wish, no padding is required."
```

However, when I add these lines in the middle (just above 'The counter mode of operation...'), the output is garbled:
```
var encryptedBytesString = aesjs.util.convertBytesToString(encryptedBytes);
var encryptedBytes = aesjs.util.convertStringToBytes(encryptedBytesString);
```
So apparently, converting to string and then back to bytes, somehow changes the original bytes.

I compared the two byte strings, and they differ at most positions, so it's not going wrong with just the first or last byte.

Background: I would like to convert the encrypted bytes your nice library creates to strings in some form of storage within an element in the DOM, and later use your stringToBytes function on these strings to get back the arrays of encrypted bytes that I can then decrypt.

But in any case, I think `stringToBytes(bytesToString(input))` should be equal to `input`.

Thanks again for your great work on this library!

**Comment by ricmoo** [comment]
This question comes up quite a bit, so I have just linked to the previous issues:

* https://github.com/ricmoo/aes-js/issues/11
* https://github.com/ricmoo/aes-js/issues/13


UTF-8 is not a means to encode binary data, and most binary data will be invalid UTF-8 encoded content. In general, this is false: `decode_utf8(encode_utf8(arbitraryData))` (regardless of language, library, etc. In many languages, such as Python, this would almost always throw an exception). If you want to get into the specifics, it has to do with ordinal bits, the moment any number in your data is `> 127`, very specific rules begin to apply to your input, which most arbitrary data will fail.


I just thought of a more obvious way to demonstrate the issue:

```
input = '45duckDuckGoose';
intEncoding = parseInt(a)
originalInput = String(a)
```

Obviously we can expect `originalInput != input`. Because the `parseInt` can only handle certain types of input. With UTF-8, it just isn't as obvious that this is what would happen.


If you wish to store strings, you have to convert your binary data to an encoding that supports arbitrary binary data; the only one I provide in the library is `hex`. So, the following will work:

```
var input = ... some binary data ...;
var hexString = bytesToString(input, 'hex');
var originalInput = stringToBytes(hexString, 'hex);
```

I have not implemented base64 in this library, but that is another common way to encode arbitrary binary data.

**Comment by wvervuurt** [comment]
Thank you kind sir for your rapid and concise response! Very educational. People like you are making open source great 👍.

Feeling like a noob for not catching this and not even finding the earlier issues.
I would like to add to these issues:

In issue #11, @fresheneesz says something:
> Might be a good idea to rename these to something like convertUTFBytesToString, cause the name makes me think its more general.

I think this is correct. Another option could be, to default to Hex instead of UTF8 for the regular functions, so that your generically named functions work on all sorts of data, and then create specific and descriptively named UTF functions.

In issue #13, you say:
> I am considering removing the functions altogether

I hope you don't! Clearly users of your library are in need of these functions and they work nicely, as long as they're being understood properly. Hopefully, just a name change or extra documentation will do. 

With regard to base64 support; you could consider simply adding calls to atob() and btoa()? This will exclude IE9 and lower, but it seems like any other modern web browser supports them. But of course it's trivial adding it myself, so it's definitely not a game breaker as much as removing the existing bytesToString and stringToBytes functions would be.

**Comment by ricmoo** [comment]
Closing this, but will open a new task to rename the functions in the next major version update.
