### ISSUE TITLE
Any benchmarks on this vs crypto-js?

### ISSUE THREAD

**Issue by chiedo** [ricmoo/aes-js#22]
Any benefit to using this over crypto-js and/or benchmarks?

Thanks!

**Comment by ricmoo** [comment]
I do not have any benchmarks. I built this mainly because, at the time, I could not find any complete implementations of AES, with all common modes and all key sizes. I use this library extensively though, and continue to maintain it. 

That said, the biggest advantage of this library is probably just size. Looking quickly at crypto-js, it looks like they do not support CBC, but that seems odd to me, so I probably just don't see it.

I thought crypto-js was abandoned by google? But I see the repository has recent commits. (Well, *a* repo).

**Comment by ricmoo** [comment]
I see in the code they do, in fact, support CBC. It is the default, which is why there is no external way to specify it. :)

**Comment by chiedo** [comment]
Thanks @ricmoo :)
