### ISSUE TITLE
Unsupported array-like object when the the iv is `atob(z0lxWTiiD8ucFdf+aLSZ+A==)`

### ISSUE THREAD

**Issue by aeroxy** [ricmoo/aes-js#37]
When using `new ModeOfOperationCBC(AES_key, atob('z0lxWTiiD8ucFdf+aLSZ+A=='))`, `function coerceArray(arg, copy)` will not be able to process the Base64Decoded iv and `throw new Error('unsupported array-like object')`.

**Comment by ricmoo** [comment]
The atob function does not return an array-like object. It returns a string. To convert a base64 decoded string (which is also a string), use something similar to:

```javascript
function convert(base64) {
    var data = atob(base64);
    var result = [];
    for (var i = 0; i < data.length; i++) {
        result.push(data.charCodeAt(i));
    }
    return result;
}
```

Unfortunately there is no safe way to take strings as input, since there is no way to know that it is actually binary encoded data, and not a legitimate string. Many people attempt to pass passwords and such into the library, which is not how a block cipher works. It is very important for crypto libraries to fail early and fail loud. Otherwise, it leads to severe security problems.

I am considering adding a base64 decode/encode library to the utilities, but there are already so many implementations available on bower and npm, this would much of the time just make the library bigger with little benefit.

It should also be noted that atob is not a standard... Just something a lot of browsers seem to include. :s

**Comment by ricmoo** [comment]
Closing this. If you have further questions, please feel free to re-open.

The atob function though, does not return an array-like object.

Thanks!
