### ISSUE TITLE
Shared ciffer between usage

### ISSUE THREAD

**Issue by Spy-Seth** [ricmoo/aes-js#4]
The actual implementation links the ciffer with the encryption key:

```javascript
var aesEcb = new aesjs.ModeOfOperation.ecb(key);
var encryptedBytes = aesEcb.encrypt(textBytes);
```

It do not allow to reuse the same ciffer instance with another key. This is especially useful to improve performance to encryp/decrypt multiple time.

Is that possible to allow us to change the used key? 

```javascript
var aesEcb = new aesjs.ModeOfOperation.ecb();
aesEcb.defineKey(key):
var firstEncryptedBytes = aesEcb.encrypt(textBytes);


aesEcb.defineKey(anotherKey):
var secondEncryptedBytes = aesEcb.encrypt(textBytes);
```

**Comment by ricmoo** [comment]
Heya Spy-Seth,

There would be no difference in calling defineKey and instantiating a new instance, as the preparation of keys should dominate any memory allocation. But regardless, other than ECB there is internal state in a mode of operation that is maintained, so you could not simply swap out the key, as you would corrupt your result. You should check out [Mode of Operations on Wikipedia](https://en.wikipedia.org/wiki/Block_cipher_mode_of_operation) to better understand the internal state.

So, while for ECB it would be *possible*, I do not believe you would gain any performance by re-using an object. What performance specifically are you trying to achieve?

For your purposes, you would be best just to keep two instances of the ModeOfOperation. If you want to be more light-weight, you could also use the aesjs.AES block cipher directly, but again, I don't think you would gain much (if anything).

**Comment by ricmoo** [comment]
I'm closing. If you have any further questions, please feel free to add to this issue or send me an e-mail. Thanks. :)

**Comment by Spy-Seth** [comment]
Sorry I forgot to reply. 

I only use ECB algorithm that's why I want it, but your right other algorithm to not manage to lazy change the key.

We are working to encrypt/decrypt lots of different values on low performance platform (ARM based server, and mobile browser). And our first test show us that the cipher creation is time consuming. So one of our first thought to want to reuse existing cipher instead of created a new one.

**Comment by ricmoo** [comment]
Heya Spy-Seth,

Yes, the expensive part of creating the cipher is actually setting the key. That's all the constructor does, is set the key. If you want to try changing the cipher's key manually, you can, and then call _prepare() on it to set it back up.

To improve performance, you can try using the AES block cipher directly, this might help since you can keep everything as an array of numbers (rather than the conversion back and forth to bytes).

Are you running in node.js? Or something more like Duktape? I don't know if you will be able to optimize much more performance out of JavaScript, as the loop is already pretty tight, but C would likely be significantly faster.

Do you need to both encrypt and decrypt at the same time? If you only need one at a time, you could modify _prepare to only generate the key you need. I've been considering making key expansion lazy, but I don't know how much that will actually gain you.

**Comment by Spy-Seth** [comment]
Ok thanks, we will try this soon.

**Comment by sylverg** [comment]
I am trying to use this library to encrypt ECB style and need to mimic decryption of an existing server side encryption. The key generated in the Java server side is 
byte[] raw = new sun.misc.BASE64Decoder().decodeBuffer(keyStr); 
Would anybody be able to help me how to represent this one in JavaScript?
