### ISSUE TITLE
What about more modes?

### ISSUE THREAD

**Issue by inf3rno** [ricmoo/aes-js#50]
As far as I know with my limited knowledge modes like XTS are good for data at rest and OCB for data transfers. CBC is not that useful without MAC. I don't get why you bother with implementing a not recommended mode like ECB and leave out the important ones.

**Comment by ricmoo** [comment]
This library focuses on the standard, [common modes of operation](https://en.wikipedia.org/wiki/Block_cipher_mode_of_operation#Common_modes).

The reason to implement these is because a large number of existing system already use these standards, so to interoperate with these systems, it is important to support the same standard.

At the time I wrote this library, there were no decent libraries which supported all the common modes and also at various key sizes. I think the landscape is still fairly sparse, but it is used in my own Ethereum [ethers.js](https://github.com/ethers-io/ethers.js/blob/master/wallet/secret-storage.js) library.

If you would like to add additional modes of operation, you could easily add them as another package that uses this as a dependency.

**Comment by inf3rno** [comment]
@ricmoo Thanks! I was thinking on writing a module or OCB. It is already implemented in python https://github.com/rex5207/OCBEncryption , so it wouldn't be not a big deal to port it to js and it is free for opensource projects now: http://web.cs.ucdavis.edu/~rogaway/ocb/license.htm I found meanwhile that there is a libsodium https://github.com/jedisct1/libsodium lib, which can be used in the browser.
