### ISSUE TITLE
My secret key is 128 but I want to use 256 blocks of data

### ISSUE THREAD

**Issue by tangzejin921** [ricmoo/aes-js#56]
Example Encryption key is "0123456789abcdef" and text is "123456"
http://tool.chacuo.net/cryptaes
(choice：ECB，pkcs7padding,256bit,utf-8)

128: Result D89D/OvFrItmxI9ct8JbAg==
256: Result 1jRJ/9iod2JHfvbCFUO2ykRZKmOdm35U0uFWw+Mha0E=

Now how do I get 256 results(1jRJ/9iod2JHfvbCFUO2ykRZKmOdm35U0uFWw+Mha0E=
) with your code

**Comment by ricmoo** [comment]
您好 @tangzejin921,

Sorry I haven't gotten to this sooner.

I'm curious how that library works. The output size should not change with the key size, since the output of AES is always 16-byte (128 bit) blocks.

The padding seems to be the wrong for both values. Under PKCS#7 padding, the string "123456" should be extended to 16 bytes. The 128-bit case you provided has a total length of 32 bytes, which is not correct (should be 16 bytes) and the 256 byte case you provided is 60 bytes, which should also be 16 bytes.

Here is an example:

```
// "123456"
var text = [ 0x31, 0x32, 0x33, 0x34, 0x35, 0x36 ];

var plaintext = aesjs.padding.pkcs7.pad(text);
// Uint8Array [ 49, 50, 51, 52, 53, 54, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10 ]

// "0123456789abcdef"
var key16 = [ 0x30, 0x31, 0x32, 0x33, 0x34, 0x35, 0x36, 0x37, 0x38, 0x39, 0x61, 0x62, 0x63, 0x64, 0x65, 0x66 ];

var ciphertext =(new aesjs.ModeOfOperation.ecb(key16)).encrypt(plaintext)
// Uint8Array [ 15, 207, 67, 252, 235, 197, 172, 139, 102, 196, 143, 92, 183, 194, 91, 2 ]

// "0123456789abcdef0123456789abcdef"
var key32 = [ 0x30, 0x31, 0x32, 0x33, 0x34, 0x35, 0x36, 0x37, 0x38, 0x39, 0x61, 0x62, 0x63, 0x64, 0x65, 0x66, 0x30, 0x31, 0x32, 0x33, 0x34, 0x35, 0x36, 0x37, 0x38, 0x39, 0x61, 0x62, 0x63, 0x64, 0x65, 0x66 ];

var ciphertext.= (new aesjs.ModeOfOperation.ecb(key32)).encrypt(plaintext)
// Uint8Array [ 9, 27, 251, 100, 120, 71, 167, 86, 88, 149, 147, 67, 201, 195, 69, 245 ]
```

Does that make sense? It seems that the page you have included is doing something very different.

**Comment by Ruffio** [comment]
@tangzejin921 can this issue be closed?
