### ISSUE TITLE
How does the counter work?

### ISSUE THREAD

**Issue by RokerHRO** [ricmoo/aes-js#67]
It looks to me that the  Counter.prototype.increment() function increments all 16 bytes of the IV / Nonce (modulo 256), so after 256 AES blocks it is the same as at the beginning.

I'd expect that nonce is initialized with a random bytes and incremented like a 256-bit-integer for each AES block.

Am I right?

**Comment by ricmoo** [comment]
Thanks @TotalTechGeek !

Exactly, it does the equivalent of "long addition", since JavaScript numbers are only compact for 53 bits of mantissa, and we require 128 bits (16 bytes). When you add 1, you must carry the overflow along until there is no longer any overflow.

Almost always, that for loop will break out of the first iteration. Only in the case of overflow will it continue, and only once for each overflow. So, `0xfe` would exit the loop after 1 iteration. `0xff` would require 2, as would `0xfeff`. `0xffff` would exit after 3 times.

Also, a counter should not be initialized to a "random" value, since both the encryption and decryption must agree on the IV. The application is required to synchronize these, *somehow*. For example, in a version 3 Ethereum JSON Secret Store, the IV is chosen randomly by the application, and included in the wallet.

**Comment by Ruffio** [comment]
@RokerHRO Has this question been answeared and this 'issue' be closed?

**Comment by Ruffio** [comment]
@ricmoo This issue/question should be closed due to the question has been answered and upon ping the originater has failed to reply within 10 days.

**Comment by ricmoo** [comment]
Closing this now, but if you have further questions, please feel free to re-open.

Thanks! :)
